Repository Azure/azure-functions-host, pull requests merged in 2020-10, with the labels that each got.

#6751 Skip parsing worker config files for dotnet apps
  src/WebJobs.Script/Workers/Rpc/Configuration/LanguageWorkerOptionsSetup.cs
  test/WebJobs.Script.Tests/Configuration/LanguageWorkerOptionsSetupTests.cs
Labels: Needs: Author Feedback

#6764 A couple logging performance improvements + Benchmarks
  WebJobs.Script.sln
  src/WebJobs.Script.WebHost/Middleware/FunctionInvocationMiddleware.cs
  src/WebJobs.Script.WebHost/Properties/AssemblyInfo.cs
  src/WebJobs.Script/Description/FunctionDescriptor.cs
  src/WebJobs.Script/Extensions/ScriptLoggingBuilderExtensions.cs
  src/WebJobs.Script/Properties/AssemblyInfo.cs
  test/Benchmarks/Extensions/ScriptLoggingBuilderExtensionsBenchmarks.cs
  test/Benchmarks/Microsoft.Azure.WebJobs.Script.Tests.Benchmarks.csproj
  test/Benchmarks/Program.cs
Labels: performance

#6765 Add environment variable for AzureMonitorDiagnosticLogger dynamic enablement
  src/WebJobs.Script.WebHost/DependencyInjection/DependencyValidator/DependencyValidator.cs
  src/WebJobs.Script.WebHost/WebScriptHostBuilderExtension.cs
  src/WebJobs.Script/Environment/EnvironmentExtensions.cs
  src/WebJobs.Script/Environment/EnvironmentSettingNames.cs
  src/WebJobs.Script/ScriptConstants.cs
  test/WebJobs.Script.Tests/Configuration/LoggingConfigurationTests.cs
  test/WebJobs.Script.Tests/Extensions/EnvironmentExtensionsTests.cs
Labels: performance

#5278 Pass context RouteData to ActionContext before execution
  src/WebJobs.Script.WebHost/Middleware/FunctionInvocationMiddleware.cs
  test/WebJobs.Script.Tests.Integration/TestScripts/CSharp/HttpTrigger-Routed/function.json
  test/WebJobs.Script.Tests.Integration/TestScripts/CSharp/HttpTrigger-Routed/run.csx
  test/WebJobs.Script.Tests.Integration/WebHostEndToEnd/CSharpEndToEndTests.cs
Labels: full-ci

#6840 Performance improvements
  src/WebJobs.Script.WebHost/Diagnostics/AzureMonitorDiagnosticLogger.cs
  src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogger.cs
  src/WebJobs.Script.WebHost/Diagnostics/SystemLogger.cs
  src/WebJobs.Script.WebHost/Extensions/IExternalScopeProviderExtensions.cs
  src/WebJobs.Script.WebHost/Middleware/FunctionInvocationMiddleware.cs
  src/WebJobs.Script.WebHost/Middleware/ResponseContextItemsCheckMiddleware.cs
  src/WebJobs.Script.WebHost/Middleware/ScriptHostRequestServiceProviderMiddleware.cs
  src/WebJobs.Script.WebHost/Routing/ScriptRouteHandler.cs
  src/WebJobs.Script.WebHost/WebJobsApplicationBuilderExtension.cs
  src/WebJobs.Script/Binding/Http/RawScriptResult.cs
  src/WebJobs.Script/Binding/Http/ScriptObjectResult.cs
  src/WebJobs.Script/Description/FunctionInvokerBase.cs
  src/WebJobs.Script/Utility.cs
  test/WebJobs.Script.Tests.Shared/TestLogger.cs
  test/WebJobs.Script.Tests/Description/FunctionInvokerBaseTests.cs
  test/WebJobs.Script.Tests/Diagnostics/FunctionInstanceLoggerTests.cs
Labels: performance
