Repository Azure/azure-functions-host, pull requests merged in 2022-01, with the labels that each got.

#8033 Figure out FUNCTIONS_WORKER_RUNTIME from function app content if Environment variable FUNCTIONS_WORKER_RUNTIME is not set
  src/WebJobs.Script/Utility.cs
  src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs
  test/WebJobs.Script.Tests/UtilityTests.cs
  test/WebJobs.Script.Tests/Workers/Rpc/RpcFunctionInvocationDispatcherTests.cs
Labels: regression

#8006 Performance: optimize order of SystemLogger.IsEnabled
  src/WebJobs.Script.WebHost/Diagnostics/SystemLogger.cs
Labels: performance

#8012 Performance: Avoid locking in ScriptLoggerFactory
  src/WebJobs.Script.WebHost/Diagnostics/ScriptLoggerFactory.cs
Labels: performance

#8013 Performance: Eliminate string allocation for LatencyEvent
  src/WebJobs.Script/Extensions/IMetricsLoggerExtensions.cs
Labels: performance

#7924 Performance: eliminate ETW date strings when disabled
  src/WebJobs.Script.WebHost/Diagnostics/EtwEventGenerator.cs
Labels: performance

#8007 Performance: eliminate PathString implicit conversion
  src/WebJobs.Script.WebHost/Middleware/VirtualFileSystemMiddleware.cs
  src/WebJobs.Script/Extensions/HttpRequestExtensions.cs
Labels: performance

#8051 Fix: race in RpcFunctionInvocationDispatcher
  src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs
Labels: bug, test

#7994 Benchmarks: update to latest libraries and add tests
  .gitignore
  WebJobs.Script.sln
  benchmarks/README.md
  benchmarks/WebJobs.Script.Benchmarks/AuthUtilityBenchmarks.cs
  benchmarks/WebJobs.Script.Benchmarks/CSharpCompilationBenchmarks.cs
  benchmarks/WebJobs.Script.Benchmarks/GrpcMessageConversionBenchmarks.cs
  benchmarks/WebJobs.Script.Benchmarks/Microsoft.Azure.WebJobs.Script.Benchmarks.csproj
  benchmarks/WebJobs.Script.Benchmarks/Program.cs
  benchmarks/WebJobs.Script.Benchmarks/RecommendedConfig.cs
  benchmarks/WebJobs.Script.Benchmarks/ScriptLoggingBuilderExtensionsBenchmarks.cs
  src/WebJobs.Script.Grpc/Properties/AssemblyInfo.cs
  src/WebJobs.Script.WebHost/Properties/AssemblyInfo.cs
  src/WebJobs.Script/Properties/AssemblyInfo.cs
  test/Benchmarks/Microsoft.Azure.WebJobs.Script.Tests.Benchmarks.csproj
  test/Benchmarks/Program.cs
Labels: performance

#8011 Performance: optimize Sanitizer for the hot path
  src/WebJobs.Script/Sanitizer.cs
  test/WebJobs.Script.Tests/SanitizerTests.cs
Labels: performance

#8057 TestHelper: fix WaitForBlobAsync null ref
  test/WebJobs.Script.Tests.Shared/TestHelpers.cs
Labels: bug, test

#7943 Performance: Eliminate Stopwatch allocations
  src/WebJobs.Script.Grpc/Channel/GrpcWorkerChannel.cs
  src/WebJobs.Script.WebHost/Diagnostics/MetricsEventManager.cs
  src/WebJobs.Script.WebHost/Features/FunctionExecutionFeature.cs
  src/WebJobs.Script.WebHost/Middleware/FunctionInvocationMiddleware.cs
  src/WebJobs.Script.WebHost/Middleware/SystemTraceMiddleware.cs
  src/WebJobs.Script/Diagnostics/MetricEvent.cs
  src/WebJobs.Script/Diagnostics/ValueStopwatch.cs
  src/WebJobs.Script/Host/ScriptHost.cs
  src/WebJobs.Script/Workers/Http/HttpWorkerChannel.cs
  src/WebJobs.Script/Workers/WorkerConcurrencyManager.cs
  test/WebJobs.Script.Tests.Integration/Diagnostics/MetricsEventManagerTests.cs
  test/WebJobs.Script.Tests/Diagnostics/ValueStopwatchTests.cs
  test/WebJobs.Script.Tests/UtilityTests.cs
Labels: needs-discussion, performance

#8056 RpcFunctionInvocationDispatcher: capture async void errors
  src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs
Labels: bug

#8031 SharedMemoryMapTests: optimize GetStream_VerifyContentMatches
  test/WebJobs.Script.Tests/Workers/SharedMemoryMapTests.cs
Labels: test, performance
