Repository Azure/azure-functions-host, pull requests merged in 2025-01, with the labels that each got.

#10681 Remove unneeded worker runtimes from linux-x64 publish
  eng/build/Workers.Dotnet.props
  eng/build/Workers.Powershell.props
Labels: area: engineering

#10709 [in-proc] Remove ExtensionMetadataGenerator from in-proc branch
  eng/ci/templates/official/jobs/build-artifacts-windows.yml
  tools/Clean.targets
  tools/ExtensionsMetadataGenerator/ExtensionsMetadataGenerator.sln
  tools/ExtensionsMetadataGenerator/build/PublicKey.snk
  tools/ExtensionsMetadataGenerator/build/metadatagenerator.props
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator.Console/ConsoleLogger.cs
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator.Console/ExtensionReference.cs
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator.Console/ExtensionsMetadataGenerator.Console.csproj
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator.Console/ExtensionsMetadataGenerator.cs
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator.Console/GlobalSuppressions.cs
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator.Console/Program.cs
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator.Console/Properties/PublishProfiles/FolderProfile.pubxml
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator.Console/runtimeconfig.template.json
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/BuildTasks/GenerateFunctionsExtensionsMetadata.cs
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/BuildTasks/RemoveRuntimeDependencies.cs
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/DotNetMuxer.cs
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/ExtensionsMetadataGenerator.csproj
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/GlobalSuppressions.cs
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/Properties/PublishProfiles/FolderProfile.pubxml
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/Targets/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.props
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/Targets/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/runtimeAssemblies-net6.txt
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/runtimeAssemblies-net8.txt
  tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/updateruntimeassemblies.ps1
  tools/ExtensionsMetadataGenerator/src/stylecop.json
  tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/ExistingRuntimeAssemblies-net6.txt
  tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/ExistingRuntimeAssemblies-net8.txt
  tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/ExtensionsMetadataGeneratorTests.cs
  tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/ExtensionsMetadataGeneratorTests.csproj
  tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/GlobalSuppressions.cs
  tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/RuntimeAssembliesUpdateTests.cs
  tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/TestStartupAttribute.cs
  tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/TestWebJobsStartup.cs
  tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/runtimeAssemblies-net6.txt
  tools/ExtensionsMetadataGenerator/test/ExtensionsMetadataGeneratorTests/runtimeAssemblies-net8.txt
  tools/ExtensionsMetadataGenerator/test/TestProject_Core21/Startup.cs
  tools/ExtensionsMetadataGenerator/test/TestProject_Core21/TestProject_Core21.csproj
  tools/ExtensionsMetadataGenerator/test/TestProject_Core22/Startup.cs
  tools/ExtensionsMetadataGenerator/test/TestProject_Core22/TestProject_Core22.csproj
  tools/ExtensionsMetadataGenerator/test/TestProject_Razor/AssemblyAttribute.cs
  tools/ExtensionsMetadataGenerator/test/TestProject_Razor/Startup.cs
  tools/ExtensionsMetadataGenerator/test/TestProject_Razor/TestProject_Razor.csproj
Labels: area: engineering

#10671 Codeql : Fix to remove exception details from the response
  src/WebJobs.Script.WebHost/Management/VirtualFileSystem.cs
Labels: Needs: Attention :wave:

#10615 Support identity auth for otel azure monitor
  release_notes.md
  src/WebJobs.Script/Diagnostics/OpenTelemetry/OpenTelemetryConfigurationExtensions.cs
  test/WebJobs.Script.Tests/Diagnostics/OpenTelemetry/OpenTelemetryConfigurationExtensionsTests.cs
Labels: area: otel

#10704 Refactor CI artifacts for release improvements
  eng/ci/official-build.yml
  eng/ci/templates/official/jobs/build-artifacts-linux.yml
  eng/ci/templates/official/jobs/build-artifacts-windows.yml
  eng/ci/templates/steps/build-site-ext.yml
  src/WebJobs.Script.SiteExtension/New-PrivateSiteExtension.ps1
  src/WebJobs.Script.SiteExtension/New-ReleaseJson.ps1
  src/WebJobs.Script.SiteExtension/Publish.SingleTFM.targets
  src/WebJobs.Script.SiteExtension/Tasks.targets
  src/WebJobs.Script.SiteExtension/WebJobs.Script.SiteExtension.csproj
  src/WebJobs.Script.SiteExtension/readme.md
Labels: area: engineering
